[package]
name = "trait_test_pbaas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
os_info = "3.5.1"
dirs = "4.0.0"
vrsc-rpc = { path = "../rust-vrsc-rpc/client" }